server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-super-secret-bank-demo-key-which-is-quite-long-0123456789}
    expiration-minutes: 120
  internal-api-key: ${APP_INTERNAL_API_KEY:internal-demo-key-please-change}

management:
  endpoints:
    web:
      exposure:
        include: health,info
